data_args:
  path: Datasets
  dataset: MAREA

train_args:
  subjects:
  - 12
  activities: # [ treadmill_slope_walk, treadmill_walk, treadmill_run, treadmill_walknrun, indoor_..., outdoor_...] + all
  - outdoor_walk
  split_walk_run: true

  events:
  - LF_HS
  oversampling: 3 # = 1 -> no oversampling
  target: future # Past, Present, Future
  class_mode: multi_label # multi_class, multi_label

  scaler: MinMax # MinMaxScaler, StandardScaler
  filter: median
  filter_window: 3

  train_test_split: middle # start, middle, end, loso, stratified
  test_size: 30 # %
  train_val_split: random # start, middle, end, loso, stratified
  val_size: 33 # %

  length: 3 # seconds
  stride: 1 # seconds
  sampling_rate: 128 # Hz

  signals:
  - Acc_x
  - Acc_y
  - Acc_z
  - Acc
  - Acc_xy
  - Acc_yz
  - Acc_xz
  before_preprocessing: true
  positions:
  - LF
  - RF
  augmentations:

  batch_size: 20
  learning_rate: 0.001
  epochs: 50

  model: Tan
  load: no

  val_scores: # [f1, precision, recall, accuracy, balanced_accuracy, classification_report, time_error]
  - f1
  - precision
  - recall
  - accuracy

  test_scores:
  - f1
  - precision
  - recall
  - accuracy
  - classification_report

  val_tables: # [confusion]
  - confusion

  test_tables:
  - confusion






